- name: Disables vagrant user
  command: usermod -L -e 1970-01-01 vagrant

- name: Allows only user login via ssh
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^AllowUsers"
              line="AllowUsers jesse"
              state=present
  notify: Restart ssh
